# Generated by Django 2.2.7 on 2019-12-08 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191205_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ManyToManyField(blank=True, default=[], to=settings.AUTH_USER_MODEL),
        ),
    ]
